#!/usr/bin/env python3

import sys
import json
import requests

data = json.load(sys.stdin)

url = data["source"]["url"]
etag = data.get("version", {}).get("etag", None)

headers = {}
if etag:
    headers["If-None-Match"] = etag

res = requests.head(url, headers=headers, allow_redirects=True)
if res.status_code == 304:
    result = []
else:
    result = [{"etag": res.headers.get("etag")}]

json.dump(result, sys.stdout)
